services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"  # REST API port
      - "6334:6334"  # gRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    environment:
      - QDRANT_ALLOW_RECOVERY=true